
ALTER TABLE documents DROP CONSTRAINT IF EXISTS documents_type_check;

ALTER TABLE documents 
ADD CONSTRAINT documents_type_check 
CHECK (type IN (
  'PRD', 'STRATEGY', 'DESIGN', 'SCHEMA', 'TECH_SPEC', 'USER_GUIDE', 'INSTRUCTIONS', 
  'BACKLOG', 'STITCH_PROMPT', 'SPRINT', 'PLANNING_CHAT', 'CONSTRUCTION_CHAT',
  'RELAY_A', 'RELAY_B', 'RELAY_C', 'RELAY_D', 'RELAY_E', 'RELAY_F'
));
